version: v1
project: integration-health

triggers:
  - name: daily-health-check
    schedule: "0 4 * * *"  # Every day at 4:00 AM
    call: workflow.py:main

connections:
  - name: openclaw
    type: http
    url: http://localhost:18789
