version: v1
project: vault-maintenance

triggers:
  - name: nightly-maintenance
    schedule: "0 1 * * *"  # Every day at 1:00 AM
    call: workflow.py:main

connections:
  - name: openclaw
    type: http
    url: http://localhost:18789
