version: v1
project: daily-briefing

triggers:
  - name: morning-briefing
    schedule: "0 6 * * *"  # Every day at 6:00 AM
    call: workflow.py:main

connections:
  - name: openclaw
    type: http
    url: http://localhost:18789
